### ISSUE TITLE
Doesn't work

### ISSUE THREAD

**Issue by realkalash** [n0a/telegram-get-remote-ip#1]
It doesn't show the IP after the call on mac

<img width="509" alt="Screenshot 2023-07-22 at 16 16 15" src="https://github.com/n0a/telegram-get-remote-ip/assets/32070904/c34f84a1-1f9a-4b81-b195-ea1c0c44d00e">

**Comment by TannicArcher** [comment]
HOST=$(host $IP) change 
 put this HOST=$(nslookup $IP) it maybe fix on mac os

**Comment by xzripper** [comment]
same

**Comment by n0a** [comment]
Thanks for the feedback! Try the new version written in python.
